### ISSUE TITLE
Autofluorescence subtraction tool

### ISSUE THREAD

**Issue by alliecreason** [goeckslab/tools-mti#18]
Inputs:
- Exposure table
- Channel/marker table
- Quantification table (feature observation matrix)

Steps:
- Divide each datapoint by exposure time of target, including Autofluorescence rounds
- Subtract each target by the autofluorescence intensities based on channel
- Clip negative numbers to zero

Output:
- Corrected quantification intensities

**Comment by CameronFRWatson** [comment]
Current plan:

- Optional exposure time correction
- 2 methods for handling AF/background:
    - SBR: Marker mean intensity values for each cell are divided by that cell's mean AF/background 
       intensity
    - AF subtraction: Subtract cell AF mean intensities, clip negatives to zero 

Ideally we'd threshold or filter cells based on adjusted values after this, but maybe not within this tool

**Comment by CameronFRWatson** [comment]
https://github.com/goeckslab/tools-mti/pull/43
