### ISSUE TITLE
Tools need explicit OOM error catcher

### ISSUE THREAD

**Issue by qiagu** [goeckslab/tools-mti#38]
The following may work for many tools.
```
<command detect_errors ="aggressive">
```
Otherwise, go with the `stdio` tag for more flexible configuration.

**Comment by qiagu** [comment]
@bgruening  Do you have any better suggestion?

**Comment by bgruening** [comment]
This looks good.

**Comment by qiagu** [comment]
@bgruening  Thanks for confirming that. I'll make a PR soon.

**Comment by CameronFRWatson** [comment]
Cleaning up issues.. this was addressed in https://github.com/goeckslab/tools-mti/pull/41
